Add unknown scenario
mx51/spi-samples-js pull request #100
Opened 2021-12-15 23:02 UTC by gopipatell

- Implemented unknown scenario
- Added test cases
- Moved TxFlow to service layer
- Added favicon

2021-12-16 00:30 UTC, mx51damon requested changes
Hi @gopipatell , I have put quite a few comments (I hope you don't mind) and welcome to have a discussion so we can have a chat and share some thoughts about the code logics in detail.

2021-12-16 00:30 UTC, mx51damon commented on src/services/spiService/index.ts
> +              schemeAppName: detail?.Response?.Data.scheme_app_name as string,
I was thinking we can remove `as string` for this line

2021-12-16 00:30 UTC, mx51damon commented on src/services/spiService/index.ts
> +              rrn: detail?.Response?.Data.rrn,
I was thinking do we need to add optional chaining operator for all `Data` object? (I am sorry, previously I didn't cover this part.)

2021-12-16 00:33 UTC, mx51damon commented on src/components/UnknownTransactionModal/index.styles.ts
> +      margin: theme.spacing(3, 1, 1, 1),
might suggest the shortcut as `theme.spacing(3, 1, 1),`

2021-12-16 12:57 UTC, gopipatell commented on src/components/OrderConfirmation/index.tsx
> +  const successStatus = currentTerminal?.txFlow?.success;
can't use `terminalTxFlowSuccessTracker` as I need unknown status

2021-12-17 00:09 UTC, mx51damon approved these changes
Thank you Gopi, nice work ~~

2021-12-17 00:09 UTC, mx51damon commented on src/components/OrderConfirmation/index.tsx
> +  const successStatus = currentTerminal?.txFlow?.success;
👌

2021-12-20 22:11 UTC, mx51damon approved these changes

2021-12-20 22:17 UTC, merged