intg-522 pairing record is missing when terminal is disconnected
mx51/spi-samples-js pull request #186
Opened 2023-06-05 23:59 UTC by gopipatell

2023-06-06 00:03 UTC, jwsandeman approved these changes
Looks Good 👍

2023-06-06 03:29 UTC, rossi-mx51 requested changes

2023-06-06 03:29 UTC, rossi-mx51 commented on src/redux/reducers/TerminalSlice/terminalsSlice.ts
> +const initialState: ITerminalState = JSON.parse(getLocalStorage('terminals')) ?? {};
Just to add extra safety, I think we should go with `getLocalStorage('terminals') ? JSON.parse(getLocalStorage('terminals')) : {}` to avoid situation where `getLocalStorage('terminals')` return undefined ( for some reasons ).

2023-06-07 00:40 UTC, rossi-mx51 approved these changes

2023-06-07 00:46 UTC, merged