Feature/INTG-506 Create a change log file for the EspressoPOS project
mx51/spi-samples-js pull request #188
Opened 2023-06-12 06:19 UTC by jwsandeman

INTG-506 Create a change log file for the EspressoPOS project

2023-06-12 23:21 UTC, rossi-mx51 commented
@jwsandeman  looks like you branched off from master to create this branch.  That's why you see all the previous commits here. 
<img width="864" alt="image" src="https://github.com/mx51/spi-samples-js/assets/119264386/3643bb1e-5e13-491f-9603-2423b6444a9c">


Let me know if you don't know how to fix it, I'll give you a hand.

2023-06-13 00:40 UTC, rossi-mx51 submitted a review, later dismissed
Approved from dev perspective. Need  Product to review as well

2023-06-13 01:40 UTC, mjancev requested changes

2023-06-13 01:40 UTC, mjancev commented on CHANGELOG.MD
> +- [INTG-491](https://mx51.atlassian.net/browse/INTG-491) Bump SPI version to 2.9.7
@jwsandeman where is the bump to use SPI 2.9.8 in the log INTG-512? cc: @rossi-mx51

2023-06-13 01:40 UTC, mjancev commented on CHANGELOG.MD
> +- [INTG-491](https://mx51.atlassian.net/browse/INTG-491) Bump SPI version to 2.9.7
I also can't see the ticket to hide P@T INTG-490

2023-06-13 01:40 UTC, mjancev commented on CHANGELOG.MD
> +- [INTG-491](https://mx51.atlassian.net/browse/INTG-491) Bump SPI version to 2.9.7
or INTG-503 for the override update

2023-06-13 02:35 UTC, jwsandeman commented on CHANGELOG.MD
> +- [INTG-491](https://mx51.atlassian.net/browse/INTG-491) Bump SPI version to 2.9.7
No worries ill have a look. I was just going off the release commits which aren't always comprehensive. I'll check the last couple of sprints' worth of tickets as well.

2023-06-15 02:35 UTC, mjancev approved these changes
LGTM

2023-06-15 04:56 UTC, rossi-mx51 approved these changes

2023-06-15 04:58 UTC, merged