Feature/INTG-573 Migrate MotelPOS pre-auth transaction flows to EspressoPOS
mx51/spi-samples-js pull request #197
Opened 2023-07-20 04:31 UTC by jwsandeman

2023-07-21 03:55 UTC, rossi-mx51 requested changes

2023-07-21 03:55 UTC, rossi-mx51 commented on src/redux/reducers/PreAuth/preAuthSelector.ts
> +  (params) => params.preAuthRef === '' || params.amount === 0
When comparing '' or 0, you can simply go 

```
(params) => !params.preAuthRef || !params.amount
```

2023-07-21 03:55 UTC, rossi-mx51 commented on src/redux/reducers/PreAuth/interfaces/index.ts
> +      value: null;
The value here can be undefined, so that when you use it, you dont need to pass it `null` value. So it would be like this: 

```
key: 'CANCEL_PRE_AUTH';
```

2023-07-21 03:55 UTC, rossi-mx51 commented on src/redux/reducers/PreAuth/interfaces/index.ts
> +      value: null;
same as above.

2023-07-21 03:55 UTC, rossi-mx51 commented on src/redux/reducers/PreAuth/preAuthSlice.ts
> +          return state;
Instead of returning state, I suggest we throw an exception here, because we don't expect to have any other key rather than those listed.

2023-07-21 03:55 UTC, rossi-mx51 commented on src/components/OrderConfirmation/OrderConfirmation.tsx
> +                          <TableCell scope="row">{preAuth.preAuthRef !== '' ? preAuth.preAuthRef : '-'}</TableCell>
A cleaner way would be:

```
preAuth.preAuthRef || '-'
```

2023-07-21 03:55 UTC, rossi-mx51 commented on src/components/OrderConfirmation/OrderConfirmation.tsx
> +                  preAuthButtonText.map((text) => (
I think this name is a bit confusing, and not descriptive enough. I would suggest change it to `preAuthActions`. 

I also notice that this variable is not used anywhere, so it would be OK to go with: 

```
['Top Up', 'Reduce', 'Extend', 'Cancel', 'Complete'].map(action) => {...}
```

2023-07-21 03:55 UTC, rossi-mx51 commented on src/components/OrderConfirmation/OrderConfirmation.tsx
>  import {
@jwsandeman 

This component is used for 4 types of transactions ( Purchase, Cashout, Refund, Preauth ), and each type has its own actions, handler, etc...  So I think this is a good time ( and a good exercise for you as well ) to break it down into 4 smaller components that are responsible for each type of transaction.

2023-07-24 23:58 UTC, jwsandeman commented on src/redux/reducers/PreAuth/interfaces/index.ts
> +      value: null;
Typescript was complaining unless i put a value in, so i changed it to undefined.

2023-07-24 23:58 UTC, jwsandeman commented on src/redux/reducers/PreAuth/interfaces/index.ts
> +      value: null;
Typescript was complaining unless i put a value in, so i changed it to undefined.

2023-07-24 23:59 UTC, jwsandeman commented on src/components/OrderConfirmation/OrderConfirmation.tsx
> +                          <TableCell scope="row">{preAuth.preAuthRef !== '' ? preAuth.preAuthRef : '-'}</TableCell>
Good point, changed.

2023-07-25 00:01 UTC, jwsandeman commented on src/components/OrderConfirmation/OrderConfirmation.tsx
> +                  preAuthButtonText.map((text) => (
Nice suggestion, changed to mapping the array directly.

2023-07-25 00:07 UTC, jwsandeman commented on src/components/OrderConfirmation/OrderConfirmation.tsx
>  import {
Good idea, done.

2023-07-25 00:09 UTC, jwsandeman commented on src/redux/reducers/PreAuth/preAuthSelector.ts
> +  (params) => params.preAuthRef === '' || params.amount === 0
Good suggestion, changed.

2023-07-25 00:13 UTC, jwsandeman commented on src/redux/reducers/PreAuth/preAuthSlice.ts
> +          return state;
Ok changed to: 
`throw new Error(`Unhandled action key: ${key}`);`

2023-07-30 23:38 UTC, rossi-mx51 requested changes
Great work, just a small thing to look at

2023-07-30 23:38 UTC, rossi-mx51 commented on src/components/OrderConfirmation/OrderConfirmation.tsx
> +          defaultAmount={0}
Should we use the `totalAmount` here instead of 0 ?

2023-07-30 23:52 UTC, jwsandeman commented on src/components/OrderConfirmation/OrderConfirmation.tsx
> +          defaultAmount={0}
Yep, good idea.

2023-07-30 23:52 UTC, rossi-mx51 approved these changes

2023-07-30 23:58 UTC, merged