INTG-573 Added fixes from QA
mx51/spi-samples-js pull request #208
Opened 2023-09-13 04:53 UTC by jwsandeman

2023-09-13 06:47 UTC, rossi-mx51 requested changes

2023-09-14 00:23 UTC, jwsandeman commented on src/components/OrderConfirmation/PreAuthOrderConfirmation.tsx
> +  function isDisabled() {
Good suggestion, done.

2023-09-14 00:23 UTC, jwsandeman commented on src/components/PaymentSummary/PaymentSummary.tsx
> +  const transactionStatus = () => {
good suggestion, done.

2023-09-14 04:35 UTC, jwsandeman commented on src/hooks/usePreAuthActions.tsx
>      if (keyPadAmount) {
Yeah good idea, ive broken this down into 3 separate functions now all with a single purpose.

2023-09-15 01:04 UTC, rossi-mx51 approved these changes
Great work 👏

2023-09-15 01:05 UTC, merged