INTG-737 Add Transaction details page
mx51/spi-samples-js pull request #222
Opened 2023-12-07 01:37 UTC by jwsandeman

This pull request adds a new Transaction details page to the application. The page includes components for displaying transaction details such as the transaction ID, type, and amount. It also includes functionality to hide certain elements (surcharge, cashout, and tipping) when the corresponding amounts are 0. This feature improves the user experience by providing more detailed information about each transaction.

2023-12-07 02:55 UTC, rossi-mx51 requested changes
Time to level up

2023-12-07 02:55 UTC, rossi-mx51 commented on src/components/ReceiptPanel/ReceiptPanel.tsx
> +  const classes = receiptPanelStyles();
in other places, the style is a custom hook. So let's be consistent and rename this useReceiptPanelStyles.

2023-12-07 02:55 UTC, rossi-mx51 commented on src/components/TransactionPage/TransactionDetailsPage/TransactionDetailsPage.tsx
> +  const currentTransactionId = pathname?.split(`${PATH_TRANSACTIONS}/`)[1];
What if the currentTransactionId is empty ? Should we redirect user to the transaction logs page, should be display some message to let users know ?

2023-12-07 02:55 UTC, rossi-mx51 commented on src/components/TransactionPage/TransactionDetailsPage/TransactionDetailsPage.tsx
> +    if (!transactionLog) return;
I think it'll be cleaner to separate the domain logic here, so let's make a new static method inside the TxLogService, 

```
export class TxLogService { 
      ....otherMethods

      static findTxByPosRefId(posRefId: string) {
             ......
      }
      
}

```

This will have several benefits: 

- If we ever need to save the TxLog to the backend, we can do it very easily.
- If we need to add some business logic into how we retrieve the transactions, we have a central place to do it as well.

2023-12-08 03:10 UTC, rossi-mx51 approved these changes

2023-12-08 03:10 UTC, rossi-mx51 commented on src/components/TransactionPage/TransactionPage.tsx
> +  const { getTransactionType, getIconByStatus } = useGetTxDetails();
Have a look at the comment below

2023-12-08 03:10 UTC, rossi-mx51 commented on src/components/TransactionPage/TransactionPage.tsx
> +                      {posRefId && (
This would still show a blank page, please move this check to the useEffect above. 

``` 
setTxLogItems(TxLogService.load().filter((tx) => dayjs(tx.completedTime).date() >= dayjs().date()));
```

-> 
``` 
setTxLogItems(TxLogService.load().filter((tx) => tx.posRefId && dayjs(tx.completedTime).date() >= dayjs().date()));
```

2023-12-08 03:18 UTC, jwsandeman commented on src/components/ReceiptPanel/ReceiptPanel.tsx
> +  useEffect(() => {
I originally had it in here, then thought a useEffect might be better. Moved it back.

2023-12-08 03:19 UTC, rossi-mx51 requested changes
Some more changes !

2023-12-08 03:25 UTC, jwsandeman commented on src/components/TransactionPage/TransactionDetailsPage/TransactionDetailsPage.tsx
> +  const transactionLog: TxLogItem[] = JSON.parse(getLocalStorage('TransactionLog'));
Ok, added this in.

2023-12-08 04:14 UTC, jwsandeman commented on src/components/TransactionPage/TransactionDetailsPage/TransactionDetailsPage.tsx
> +
Ok, good idea. added.

2023-12-08 05:16 UTC, jwsandeman reviewed
Ok ive addressed all of your comments. Will submit another PR with the changes shortly.

2023-12-10 23:40 UTC, rossi-mx51 approved these changes
Great work 👏

2023-12-10 23:55 UTC, merged