Feature/intg 732
mx51/spi-samples-js pull request #223
Opened 2023-12-08 03:20 UTC by rossi-mx51

2023-12-11 23:04 UTC, ruoxin-mx51 commented on src/redux/reducers/PayAtTableSlice/payAtTableSlice.ts
> +        tableId: state.tables.length + 1,
If we delete the non-last table and add a new one, we will have duplicated table id

2023-12-11 23:15 UTC, ruoxin-mx51 commented on src/components/SettingsPage/PatAtTablePanel.tsx
> +  const [patConfig, setPatConfig] = useState<PayAtTableConfig>(spiService.state.patConfig);
When the pat settings are changed, the updates are not reflected unless refresh the page

2023-12-12 04:26 UTC, rossi-mx51 commented on src/components/PayAtTablePage/Table/Table.tsx
> +  selectedOperatorId,
Good point !

2023-12-12 04:30 UTC, rossi-mx51 commented on src/components/SettingsPage/PatAtTablePanel.tsx
> +  const [patConfig, setPatConfig] = useState<PayAtTableConfig>(spiService.state.patConfig);
It will change, because we're controlling the state internally.  So the cycle will be like this:

- Component first mounted:  patConfig is set to whatever is in the spiService.state.patConfig initially 
- Whenever the value changed, the setPatConfig will be called with the new value -> the settings is changed.
- When clicking save, the config will be updated in the spiService.state.patConfig with the most up-to-date state.

2023-12-12 04:30 UTC, rossi-mx51 commented on src/components/SettingsPage/PatAtTablePanel.tsx
> +        Pat At Table
good spot

2023-12-12 04:32 UTC, rossi-mx51 commented on src/redux/reducers/PayAtTableSlice/payAtTableSlice.ts
> +        tableId: state.tables.length + 1,
good point, will account for this

2023-12-12 04:34 UTC, rossi-mx51 commented on src/components/PayAtTablePage/Table/Table.tsx
> +  selectedOperatorId,
but we can't remove line 42, because it's a different lint rule

2023-12-12 05:14 UTC, ruoxin-mx51 commented on src/components/SettingsPage/PatAtTablePanel.tsx
> +  const [patConfig, setPatConfig] = useState<PayAtTableConfig>(spiService.state.patConfig);
I've found that if we change the settings and click save button, navigate to other page, and navigate back to "pay at table settings", the settings will be reverted to previous status.

2023-12-12 22:28 UTC, rossi-mx51 commented on src/components/SettingsPage/PatAtTablePanel.tsx
> +  const [patConfig, setPatConfig] = useState<PayAtTableConfig>(spiService.state.patConfig);
@rossi-mx51  good one, fixed it :)

2023-12-13 00:26 UTC, ruoxin-mx51 requested changes
Looks good mate, just one more small issue and needs rebase

2023-12-13 00:26 UTC, ruoxin-mx51 commented on src/redux/reducers/PayAtTableSlice/payAtTableSlice.ts
> +          tableId: i + 1,
Also need to update label
```
label: `Table #${i + 1}`,
```

2024-01-15 03:28 UTC, ruoxin-mx51 approved these changes
🎉

2024-01-15 05:45 UTC, merged