INTG-702 and 794 add terminal list action
mx51/spi-samples-js pull request #243
Opened 2024-02-27 04:20 UTC by gopipatell

- Terminal action button
- About page available for terminals in all pairing states
- Bug fix  INTG-793

2024-02-28 03:54 UTC, rossi-mx51 requested changes
Looks good, just a few things to consider.

2024-02-28 03:54 UTC, rossi-mx51 commented on src/components/PairPage/PairForm/PairConfiguration/PairConfiguration.tsx
> +        dispatch(
Rather than dispatching 4 times, it's cleaner to have another action to update the whole form :)

2024-02-28 03:54 UTC, rossi-mx51 commented on src/components/PairPage/PairForm/PairForm.tsx
> +  const pairBtnDisabled = !currentTerminal && useAppSelector(isPairDisabled);
We're breaking the first rule of a hook here. 


![image](https://github.com/mx51/spi-samples-js/assets/119264386/618c8aed-e580-47ff-8652-f9bf42563950)

FYI - @jwsandeman

2024-02-28 03:54 UTC, rossi-mx51 commented on src/components/PairPage/PairPage.tsx
> +  const { id }: { id: string } = useParams<{ id: string }>();
This is all you need:

const { id } = useParams<{ id: string }>();

2024-02-28 03:54 UTC, rossi-mx51 commented on src/components/PairPage/PairPage.tsx
> +  const currentTerminal = id ? useAppSelector<ITerminalProps>(terminalInstance(id)) : undefined;
Please look at the above comment

2024-02-28 03:54 UTC, rossi-mx51 commented on src/components/PairPage/PairForm/PairConfiguration/PairConfiguration.tsx
> +export default function PairConfiguration({ currentTerminal }: ITerminal): React.ReactElement {
The main purpose of passing the currentTerminal here is just to update the pairForm Slice ?  If so, why not doing it in the parent component i.e  PairPage ? 


```
    if (!currentTerminal) {
      dispatch(resetPairForm()); // reset paired form when required
    } else {
        ....logic for updating 
    }
```

2024-02-28 03:54 UTC, rossi-mx51 commented on src/components/TerminalsPage/TerminalsPage.tsx
> +  const terminalList = Object.entries(terminals)
```
const {_persist, ...terminalList} = terminals
```
can do the trick, and it's much cleaner.

2024-02-28 22:50 UTC, ruoxin-mx51 commented on src/components/TerminalsPage/TerminalsPage.tsx
> +  const terminalList = Object.entries(terminals)
I've made some changes to `terminalsSliceSelector` (see [here](https://github.com/mx51/spi-samples-js/pull/238/files#diff-93b8e6fd6eb7657e92e1647c38b9c971ce88388bc5a5e70b9b6ba04c2b065651)) now `useSelector(terminalList)` will return the real terminal list (array) without `_persist`

2024-03-04 00:50 UTC, rossi-mx51 requested changes
Looks great @gopipatell.  Just one last thing to resolve: 

The package-lock.json has 4555 changes, while we didn't try to install any new packages in this PR. This probably a node-incompatible issue, so can you try to remove node_module, do npm i using the latest version of node to see if it helps ?

2024-03-04 02:04 UTC, rossi-mx51 requested changes
There should be no changes on the package-lock.json

2024-03-04 05:21 UTC, rossi-mx51 approved these changes

2024-03-04 05:25 UTC, merged