INTG-845 Refactor PaymentSummary into re-usable component and impleme…
mx51/spi-samples-js pull request #258
Opened 2024-03-21 00:35 UTC by jwsandeman

…nt in OrderFinished, TransactionDetails and SplitPage components

2024-03-22 05:21 UTC, ruoxin-mx51 requested changes
The new receipt looks great. Just some suggestions about the structure.

2024-03-22 05:21 UTC, ruoxin-mx51 commented on src/components/OrderFinished/OrderFinished.tsx
> +  const [currentTransaction, setcurrentTransaction] = useState<TxLogItem>();
Could the setter name be changed to `setCurrentTransaction`?

2024-03-22 05:21 UTC, ruoxin-mx51 commented on src/components/PaymentSummary/OrderButtons.tsx
The OrderButton has taken on too many responsibilities that are not its own. I recommend changing to take 2 parameters: the button name and the callback function when the button is clicked. Or just take the whole button as a parameter.

2024-03-22 05:21 UTC, ruoxin-mx51 commented on src/components/PaymentSummary/PaymentSummary.tsx
> +                {splitTransaction ? (
Similar to OrderButton, I suggest adding a "custom OrderInfo" parameter and pass the SplitSummary as a custom OrderInfo from SplitReceipt page. With this change the PaymentSummary component will no longer need to know the details of split transaction.

2024-03-27 04:19 UTC, rossi-mx51 approved these changes

2024-03-27 05:06 UTC, closed without merging