ITNG-962 Fix terminals and persist:terminal out of sync causing a bro…
mx51/spi-samples-js pull request #268
Opened 2024-07-03 23:40 UTC by rossi-mx51

The issue is we store terminal information in redux:persist and self-managed localStorage.  Terminal infor saved in self-managed localStorage is used to initiate SPI library instance, and   the one in redux:persist is used in the terminal page to display to users. We don't have single source of truth,  so when they're mismatch ( the terminal is removed in self-managed localStorage, but haven't removed in redux:persist will cause a crash ).

2024-07-03 23:43 UTC, rossi-mx51 commented on src/components/PairPage/PairPage.tsx
> +          value: currentTerminal.deviceAddress,
the device address will now only show IP or FQDN address without the protocol ( ws or wss ). So removing this `split` logic.

2024-07-03 23:44 UTC, rossi-mx51 commented on src/services/spiService/index.ts
> +  spiInstances: ITerminals = {};
Renaming this to spiInstances to indicate that the spiService will only manage SPI instances, not terminal information.

2024-07-04 05:49 UTC, MicheilCathcart requested changes
Thanks mate looks pretty good, much tidier. I think only a tiny thing and then looking into where we should still remove from local storage. Are the other circumstances where `removeTerminalInstance` was being called still a relevant reason to remove the terminal?

2024-07-04 05:49 UTC, MicheilCathcart commented on src/services/spiService/index.test.ts
> -      acquirerCode: defaultMockPairFormParams.acquirerCode.value,
Just an unused import now for `defaultMockPairFormParams`

2024-07-04 08:26 UTC, rossi-mx51 commented
@MicheilCathcart  thanks for reviewing the PR mate. I'm not sure what you meant here 


> Are the other circumstances where removeTerminalInstance was being called still a relevant reason to remove the terminal?

2024-07-05 00:00 UTC, MicheilCathcart commented
> @MicheilCathcart thanks for reviewing the PR mate. I'm not sure what you meant here
> 
> > Are the other circumstances where removeTerminalInstance was being called still a relevant reason to remove the terminal?

Just with old logic was if pairing failed for something like `spiAutoAddressResolutionFailed`, we would totally remove the terminal instance from local storage. (Still displaying to the users via redux persist which was a mismatch). Was there a reason why removing the terminal as an instance option completely was the right thing to do? Or do we just leave it to the users to remove a terminal if it reaches a state where pairing would not be possible?

2024-07-05 00:54 UTC, MicheilCathcart commented
> > @MicheilCathcart thanks for reviewing the PR mate. I'm not sure what you meant here
> > > Are the other circumstances where removeTerminalInstance was being called still a relevant reason to remove the terminal?
> 
> Just with old logic was if pairing failed for something like `spiAutoAddressResolutionFailed`, we would totally remove the terminal instance from local storage. (Still displaying to the users via redux persist which was a mismatch). Was there a reason why removing the terminal as an instance option completely was the right thing to do? Or do we just leave it to the users to remove a terminal if it reaches a state where pairing would not be possible?

After chatting - have decided that the decision around this in the past is okay to change.

2024-07-05 00:54 UTC, MicheilCathcart approved these changes
Thanks mate awesome stuff. Have not checked out Redux persist before was good to take a look

2024-07-05 01:32 UTC, merged