[INTG-996] add: pairing demo
mx51/spi-samples-js pull request #270
Opened 2024-07-17 05:26 UTC by MicheilCathcart

https://mx51.atlassian.net/browse/INTG-996?atlOrigin=eyJpIjoiY2UxMmQ4NTY4NTg2NDNlNmE2OGFkMTFlYTZhMmUzOGUiLCJwIjoiaiJ9

## Notes

Just for internal testing so no tests, basic ui etc. Will not merge this into main. If wanting to test hit me up for an API key to replace and also I can provide a MXA build with spi cloud pairing functionality.

2024-07-17 06:18 UTC, MicheilCathcart commented on src/components/SpiCloudPairingNewPage/SpiCloudPairingNewPage.tsx
> +      const response = await fetch(pairingUrl, {
@alistair-mx51 here is where the pairing request is being made

2024-07-24 03:35 UTC, rossi-mx51 requested changes
Nice work man. 

Just a thing and a potential issue with cancel pairing.

2024-07-24 05:38 UTC, MicheilCathcart commented on src/components/SpiCloudPairingNewPage/SpiCloudPairingNewPage.tsx
> +              onClick={() => onCancel}
Thanks mate

2024-07-24 05:41 UTC, MicheilCathcart commented on src/components/SpiCloudPairingNewPage/SpiCloudPairingNewPage.tsx
> +        {!pairSuccess && (
Cool looks tidy

2024-07-24 06:25 UTC, rossi-mx51 approved these changes
Looks good, thanks mate. 

A smallish suggestion, but it's not important. Approving now, we can take a look at that in the next PR where we add more envs.

2024-07-24 06:25 UTC, rossi-mx51 commented on src/redux/reducers/SpiCloudSettingsSlice/spiCloudSettingsSlice.ts
> +  initialState: {
Maybe abstract this initialState out to avoid some duplication ?

2024-07-24 06:30 UTC, merged