[INTG-1038][INTG-1040] Add spi cloud pairing based on designs
mx51/spi-samples-js pull request #273
Opened 2024-10-03 04:20 UTC by MicheilCathcart

https://mx51.atlassian.net/browse/INTG-1040
https://mx51.atlassian.net/browse/INTG-1038

Notes - 
- Removed husky pre-commit tests
- Added @material-ui/lab for alert functionality
- Now getting ENV meta data to show / hide live vs dev ui
- Loosely based on these designs, however as it was decided to not use Chameleon UI in Espresso POS yet, I have used the existing MUI styling and applied the layout / text changes from the newer design - https://www.figma.com/design/OcYyVbjD2ejFQA622uC6gA/Feature%3A-Integrations-Pairing?node-id=370-11779&node-type=canvas&t=VtCzocCS3wFDmInl-0 
- I have removed tests that broke due to UI changes, I do not see the value in them. Can add them back in and update if we think they are worthwhile. 
- Changed the way the settings tabs work so they now have a corresponding route, this is the allow the react-router-dom `Prompt` to show a dialog when location changes and there is unsaved changes
- Deleted the first iteration of spi cloud, that had its own pairing and settings page.

2024-10-03 23:53 UTC, sebtoombs requested changes
Awesome work dude. Great work figuring out how to fight redux. Few changes here, I assume there will maybe be more review necessary when you push some changes

2024-10-03 23:53 UTC, sebtoombs commented on src/components/SettingsPage/IntegrationSettingsPanel.tsx
> +  const handleBlockedNavigation = () => `You have unsaved changes. Are you sure you want to go to leave this page?`;
Unsure if it helps/simplifies, but I think react router has a component for this: https://v5.reactrouter.com/core/api/Prompt

2024-10-03 23:53 UTC, sebtoombs commented on src/components/SettingsPage/SettingsPage.tsx
> +  useEffect(() => {
I think this would be better suited to a `useMemo`? Looks like "derived state".

So, lose the `useState` and 

```
const tabIndex = useMemo(() => {
  switch....
  return activeTabIndex;
}, [location.pathname])
```

2024-10-03 23:53 UTC, sebtoombs commented on src/components/SettingsPage/SettingsPage.tsx
> +                </Route>
Realised we will also need to add a "Catch all" /fall through redirect to catch anything that isn't the above routes and redirect to `/settings`

Something like
`<Redirect from="*" to="/settings" />`
at the end of this switch

2024-10-03 23:53 UTC, sebtoombs commented on src/index.tsx
> +      <CurrentEnvInitializer />
There's an issue with this implementation - the rest of the application expects the env to be available immediately and synchronously, whereas this will initialise the env and continue rendering the app in parallel/asynchronously (no guarantee that env exists when the first thing renders)

I'd suggest either

1. refactor the app to get env data from a hook/async/non-dependent access
2. wrap the rest of the app in this "provider" e.g. `<CurrentEnvInitializer><Rest of app></CurrentEnvInitializer>`

2024-10-03 23:53 UTC, sebtoombs commented on src/components/SettingsPage/IntegrationSettingsPanel.tsx
> +import { Action, Location } from 'history';
Unused import

2024-10-04 04:08 UTC, MicheilCathcart commented on src/components/SettingsPage/IntegrationSettingsPanel.tsx
> +  const handleBlockedNavigation = () => `You have unsaved changes. Are you sure you want to go to leave this page?`;
Nice simplified this to pass directly to message prop on prompt. I had this function doing some other things in the past but it is no longer required :D

2024-10-04 04:08 UTC, MicheilCathcart commented on src/components/SettingsPage/SettingsPage.tsx
> +                </Route>
Good catch thanks!

2024-10-04 04:10 UTC, MicheilCathcart commented on src/components/SettingsPage/SettingsPage.tsx
> +  useEffect(() => {
Very nice thanks for the reminder around derived state

2024-10-08 22:56 UTC, sebtoombs requested changes

2024-10-08 22:56 UTC, sebtoombs commented on src/components/PairPage/PairingSteps/SpiCloudPairingSteps.tsx
> +  console.log('Render pairing steps');
Lost log line

2024-10-08 22:56 UTC, sebtoombs commented on src/components/PairPage/PairingSteps/SpiCloudPairingSteps.tsx
> +  const [state, dispatch] = useReducer(reducer, initialState);
Is this unused?

2024-10-08 22:56 UTC, sebtoombs commented on src/components/PairPage/SpiCloudPairing/SpiCloudCodeConfirmation.tsx
> +type Props = {
Minor, but try and use `interface` unless you need to, apparently interfaces are more performant 🤷

2024-10-08 22:56 UTC, sebtoombs commented on src/components/PairPage/SpiCloudPairing/SpiCloudPairing.tsx
> +        dispatch({ type: 'error' });
Normally I'd `throw` here - this way your `catch` will get both network errors & non-200 errors

2024-10-08 22:56 UTC, sebtoombs commented on src/components/PairPage/SpiCloudPairing/SpiCloudPairing.tsx
> +    dispatch({ type: 'initial' });
Does the cancel action need to `abort` any in flight request?

https://developer.mozilla.org/en-US/docs/Web/API/AbortController

2024-10-08 22:56 UTC, sebtoombs commented on src/components/PairPage/SpiCloudPairing/SpiCloudPairing.tsx
> +      {!state.pairSuccess && !state.isLoading && <SpiCloudPairingForm onSubmit={onFormSubmit} />}
I don't know what the rest of this app does, and I don't know if it matters, but do we care that we're hiding the whole form while it's loading?

2024-10-08 22:56 UTC, sebtoombs commented on src/components/PairPage/SpiCloudPairing/SpiCloudPairingReducer.tsx
Nice! 🤩

2024-10-08 23:20 UTC, MicheilCathcart commented on src/components/PairPage/SpiCloudPairing/SpiCloudPairingReducer.tsx
Thanks for your help with this, loving the reducer waaaay tidier :D

2024-10-08 23:20 UTC, MicheilCathcart commented on src/components/PairPage/SpiCloudPairing/SpiCloudPairing.tsx
> +      {!state.pairSuccess && !state.isLoading && <SpiCloudPairingForm onSubmit={onFormSubmit} />}
I don't think so, this wasn't part of the design so I just put it in there for a bit of feedback

2024-10-08 23:52 UTC, MicheilCathcart commented on src/components/PairPage/PairingSteps/SpiCloudPairingSteps.tsx
> +  const [state, dispatch] = useReducer(reducer, initialState);
Thanks mate yep :)

2024-10-09 02:00 UTC, MicheilCathcart commented on src/components/PairPage/SpiCloudPairing/SpiCloudPairing.tsx
> +        dispatch({ type: 'error' });
Sounds good

2024-10-09 02:07 UTC, MicheilCathcart commented on src/components/PairPage/SpiCloudPairing/SpiCloudPairing.tsx
> +    dispatch({ type: 'initial' });
In this case they don't see this until they request is complete and pairing code has been returned. It is more just a UI sprinkle to return to prior state, they also need to cancel on the terminal side.

2024-10-09 02:38 UTC, sebtoombs commented on src/components/PairPage/SpiCloudPairing/SpiCloudPairing.tsx
> +    dispatch({ type: 'initial' });
Yeah, but if the user clicks `cancel`, and then an in flight request either resolves or rejects, your order of operations will be;
`dispatch - initial`
`dispatch - success/error`
Given that your reducer isn't an actual finite state machine (any state can proceed to any other state), this might be odd?

2024-10-09 04:24 UTC, sebtoombs approved these changes
Super duper massive effort many thanks

2024-10-09 04:24 UTC, merged