[FE-19] add: unpairing
mx51/spi-samples-js pull request #276
Opened 2024-11-01 04:17 UTC by MicheilCathcart

2024-11-04 22:31 UTC, hayden-mx51 commented on src/components/CurrentEnvInitializer/CurrentEnvInitialiser.tsx
> +      dispatch(setCurrentEnv('DEV'));
Thanks for this 🙏

2024-11-04 22:32 UTC, hayden-mx51 commented
It works! I guess we don't do confirmation dialogs in espresso pos 🙈

2024-11-05 00:02 UTC, sebtoombs requested changes
Super job! It works!
Minor one or 2

2024-11-05 00:02 UTC, sebtoombs commented on src/components/TerminalsPage/SpiCloudPairingList/SpiCloudPairingActionMenu.tsx
> +  const open = Boolean(anchorEl);
I know I'm always banging on about variable names, and it's really not important in this project, but I had to figure out the purpose of this one. `isOpen` would fit our rules better....

2024-11-05 00:02 UTC, sebtoombs commented on src/components/TerminalsPage/SpiCloudPairingList/SpiCloudPairingListReducer.tsx
Feels like we're really starting to stress this pattern.... maybe we should add/should have added tanstack query? (not here, just a comment)

2024-11-05 00:25 UTC, MicheilCathcart commented on src/components/PairPage/SpiCloudPairing/SpiCloudPairing.tsx
> +    // TODO: Update ENV to be the env returned from pairing response instead of maintaining this in reducer.
Not sure, just something that had been mentioned in the past that at some point we will get env and tenant in the response

2024-11-05 02:20 UTC, MicheilCathcart commented on src/components/TerminalsPage/SpiCloudPairingList/SpiCloudPairingListReducer.tsx
A decent idea for sure, I really just wanted another go at a reducer haha.

2024-11-05 02:21 UTC, MicheilCathcart commented
@hayden-mx51 I like your naming of all the pairing stuff better as well, will leave as is for now but keen to switch it over to your convention in your PR

2024-11-05 02:22 UTC, MicheilCathcart commented on src/utils/common/signRequest.ts
> +export const signRequest = async (
Cool a good idea, I can change this up.

2024-11-05 02:23 UTC, MicheilCathcart commented on src/utils/common/signRequest.ts
> +  // Line breaks are required for the signature to be valid
All props go to @hayden-mx51 for figuring out this wackiness haha

2024-11-05 02:24 UTC, MicheilCathcart commented
> It works! I guess we don't do confirmation dialogs in espresso pos 🙈

Haha yeah I don't think we have even brought in a dialog anywhere yet.

2024-11-05 23:54 UTC, MicheilCathcart commented on src/components/PairPage/SpiCloudPairing/SpiCloudPairing.tsx
> +    // TODO: Update ENV to be the env returned from pairing response instead of maintaining this in reducer.
Added ticket now - https://mx51.atlassian.net/browse/FE-69?atlOrigin=eyJpIjoiMGI4MzQxMWI2YWYyNDI1YThmM2E0ZmNhMmQ0MjYwMGEiLCJwIjoiaiJ9 thanks mate

2024-11-05 23:56 UTC, MicheilCathcart commented on src/utils/common/signRequest.ts
> +export const signRequest = async (
Thinking about this more, I am almost certain POS will ask for an example of this when they get confused, so providing them a plug and play function either in docs or sending through will alleviate some grief. This is a good playground for what that could look like

2024-11-06 03:29 UTC, sebtoombs requested changes

2024-11-06 03:29 UTC, sebtoombs commented on src/components/TerminalsPage/SpiCloudPairingList/SpiCloudPairingActionMenu.tsx
> +        ...signedRequest,
Probably don't need to spread this?

2024-11-06 03:29 UTC, sebtoombs commented on src/utils/common/signRequest.ts
> +  requestBody: unknown,
Given this can be empty (e.g. a `GET`) I'd probably shuffle it to the end? Avoids the empty object you've used (`{}`). Could probably also default the method to `GET` but that's up to you.
If you wanted to get really clever, you'd do an overload per method making body either not available (`GET`, `OPTIONS`, ...etc?) or available. But that's overkill 😄

2024-11-06 05:17 UTC, sebtoombs approved these changes

2024-11-06 05:25 UTC, merged