Add terminal list & no terminal page
mx51/spi-samples-js pull request #61
Opened 2021-07-28 05:49 UTC by gopipatell

- Added no terminal page
- Added terminal page

2021-07-28 06:53 UTC, DamengRandom requested changes

2021-07-28 06:53 UTC, DamengRandom commented on src/components/TerminalsPage/TerminalList/index.tsx
> +              <TableCell align="right">Eftpos address</TableCell>
Uppercase EFTPOS? Or shall we confirm with team?

2021-07-28 06:53 UTC, DamengRandom commented on src/components/TerminalsPage/TerminalList/index.tsx
> +function TerminalList(props: { terminals: Array<Terminal> }): React.ReactElement {
I was thinking If we write like this, we would remove line 19.
`function TerminalList({ terminals: Array<Terminal> }): React.ReactElement {`

2021-07-28 06:53 UTC, DamengRandom commented on src/components/TerminalsPage/TerminalList/index.tsx
> +                <TableCell align="right">
From Jess design, it looks the content are aligned left instead of right, and I was curious about `align="right"`.

2021-07-28 06:53 UTC, DamengRandom commented on src/components/TerminalsPage/index.tsx
> +import { Box, Button, Container, Typography, Link } from '@material-ui/core';
alphabetical order for `Link`?

2021-07-28 06:53 UTC, DamengRandom commented on src/components/TerminalsPage/TerminalList/index.styles.ts
> +    chip_connected: {
Shall we keep camelCase? (consistency consideration?)

2021-07-28 06:53 UTC, DamengRandom commented on src/definitions/constants/themeStylesConfigs.ts
> +export const CHIP_BACKGROUND_SUCCESS_COLOR = '#E1F4EC';
alphabetical order for chip constants?

2021-07-28 06:53 UTC, DamengRandom commented on src/components/TerminalsPage/index.tsx
> +import TerminalList from './TerminalList';
alphabetical order for these components import?

2021-07-28 06:53 UTC, DamengRandom commented on src/components/TerminalsPage/index.test.tsx
> +    // Assert(
Shall we remove the single bracket?

2021-07-28 06:53 UTC, DamengRandom commented on src/components/NoTerminalPage/index.tsx
> +      <Grid item sm={12}>
If the purpose is keep full grid width for the smallest screen, shall we use `xs={12}`?

2021-07-28 06:53 UTC, DamengRandom commented on src/images/UnpluggedIcon.svg
> +<path d="M20.3495 34.4129C20.0899 34.4129 19.8362 34.336 19.6203 34.1918C19.4045 34.0477 19.2363 33.8427 19.1369 33.6029C19.0375 33.3632 19.0114 33.0993 19.062 32.8447C19.1126 32.5901 19.2375 32.3563
For the `fill` attribute, shall we use `fill="currentColor"` as Matt suggested before?

2021-07-28 07:02 UTC, gopipatell commented on src/components/TerminalsPage/index.tsx
> +import { Box, Button, Container, Typography, Link } from '@material-ui/core';
Shall we use ESlint to automatically rather than we manually do it?

2021-07-28 07:11 UTC, gopipatell commented on src/components/TerminalsPage/TerminalList/index.tsx
> +function TerminalList(props: { terminals: Array<Terminal> }): React.ReactElement {
I tried that but this doesn't work. We have to create another type like IProps and wrap the terminals inside. Then only work. I think this is more verbose and better then creating another type.

2021-07-28 07:26 UTC, DamengRandom commented on src/components/TerminalsPage/index.tsx
> +import { Box, Button, Container, Typography, Link } from '@material-ui/core';
Would you like to try this one? https://github.com/lydell/eslint-plugin-simple-import-sort

2021-07-28 07:32 UTC, DamengRandom commented on src/components/TerminalsPage/TerminalList/index.tsx
> +function TerminalList(props: { terminals: Array<Terminal> }): React.ReactElement {
Try this?

`interface ITerminals {
  terminals: Array<Terminal>;
}
// @TODO we need to put above interface definition into a separate file

function TerminalList({ terminals }: ITerminals): React.ReactElement {`

2021-07-28 07:37 UTC, DamengRandom commented on src/components/TerminalsPage/TerminalList/index.tsx
> +function TerminalList(props: { terminals: Array<Terminal> }): React.ReactElement {
Sorry @gopipatell, this one can be optional for change, we can keep your solution, I would like to show you an alternative way to do it ~

2021-07-28 07:39 UTC, DamengRandom commented on src/components/TerminalsPage/index.tsx
> +import { Box, Button, Container, Typography, Link } from '@material-ui/core';
If it's not working well, we can just keep it manually for now. 🙌

2021-07-28 08:25 UTC, gopipatell commented on src/components/TerminalsPage/index.test.tsx
> +    // Assert(
Doesn't work if I remove the bracket since container is the nested object of the return type

2021-07-28 08:43 UTC, DamengRandom commented on src/components/TerminalsPage/index.test.tsx
> +    // Assert(
Hi @gopipatell , I mean this: `// Assert(` to `// Assert`, 🤗

2021-07-28 11:03 UTC, gopipatell commented on src/components/TerminalsPage/index.test.tsx
> +    // Assert(
hahaha got it

2021-07-29 00:18 UTC, DamengRandom commented on src/components/TerminalsPage/TerminalList/index.styles.ts
> +      minWidth: 650,
I was thinking using grid, adjust by the percentage when screen is smaller, like mobile devices?

2021-07-29 00:19 UTC, DamengRandom commented on src/images/UnpluggedIcon.svg
> +<svg width="64" height="65" viewBox="0 0 64 65" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
Sorry, @gopipatell, it was my fault, I felt like this one got different colors for different paths. Thus, we probably need to use the hardcoded colors, and we don't change the fill to currentColor for svg tag, shall we keep the original exported/copied fill color value code from Figma instead of currentColor for svg tag (line 1)?

2021-07-29 00:19 UTC, DamengRandom commented on src/components/NoTerminalPage/index.styles.ts
> +      padding: '2rem 0 1rem 0',
theme.spacing(4, 0, 2, 0)?

2021-07-29 00:21 UTC, DamengRandom commented on src/components/NoTerminalPage/index.styles.ts
> +      marginTop: '1rem',
theme.spacing(2)?

2021-07-29 00:21 UTC, DamengRandom commented on src/components/TerminalsPage/TerminalList/index.styles.ts
> +      marginTop: '1rem',
theme.spacing(2)?

2021-07-29 00:21 UTC, DamengRandom commented on src/components/TerminalsPage/index.tsx
> +import { Box, Button, Container, Typography, Link } from '@material-ui/core';
As we discussed, this one we will open by another PR 🙌

2021-07-29 00:23 UTC, DamengRandom commented on src/images/UnpluggedIcon.svg
> +<svg width="64" height="65" viewBox="0 0 64 65" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
fill="none" is the value I bet

2021-07-29 01:48 UTC, gopipatell commented on src/components/TerminalsPage/TerminalList/index.styles.ts
> +      minWidth: 650,
In this case table element would be right element to use since it is a tabular data. I have fixed the responsiveness of the table when screen is small.

2021-07-29 03:10 UTC, DamengRandom approved these changes

2021-07-29 03:11 UTC, DamengRandom commented on src/components/TerminalsPage/TerminalList/index.styles.ts
> +      minWidth: 650,
Nice one

2021-07-29 07:04 UTC, mattgresham approved these changes
Nice Work!

2021-07-29 07:11 UTC, merged